#
# Build the Handbook with just the content from this chapter.
#
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/books/handbook/security/Makefile 30 2012-09-20 17:39:11Z ebrandi@fugspbr.org $
#

CHAPTERS= 	security/chapter.sgml

VPATH=		..

MASTERDOC=	${.CURDIR}/../${DOC}.${DOCBOOKSUFFIX}

DOC_PREFIX?= 	${.CURDIR}/../../../..

.include "../Makefile"
