#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
# 
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/books/website/Makefile 9 2012-09-19 01:19:11Z ebrandi@fugspbr.org $
#

MAINTAINER=ebrandi@fugspbr.org

DOC?= book

FORMATS?= html-split
NO_TIDY="YES"

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=  book.sgml 

URL_RELPREFIX?= ../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"

