# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.4
#
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/books/Makefile.inc 2 2012-09-18 19:11:04Z ebrandi@fugspbr.org $

DESTDIR?=	${DOCDIR}/pt_BR.ISO8859-1/books/${.CURDIR:T}
