# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: 1.10
#
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/books/Makefile 102 2012-09-28 01:49:05Z ebrandi@fugspbr.org $

SUBDIR+= faq
SUBDIR+= fdp-primer
SUBDIR+= handbook

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
