# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/java/docs/Makefile 164 2012-10-04 20:43:02Z ebrandi@fugspbr.org $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS =	faq.xml
DOCS+=	howtoports.xml
DOCS+=	newbies.xml
DOCS+=	tutorials.xml
DOCS+=	performance.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
