# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/advocacy/Makefile 164 2012-10-04 20:43:02Z ebrandi@fugspbr.org $
#
# Makefile for the advocacy site

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   index.xml
DOCS+=	myths.xml
DOCS+=	whyusefreebsd.xml
.include "${DOC_PREFIX}/share/mk/web.site.mk"
