#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/articles/freebsd-questions/Makefile 165 2012-10-04 21:26:02Z ebrandi@fugspbr.org $
#
# Original revision: r38826
#
# Article: How to get best results from the FreeBSD-questions mailing list

MAINTAINER=doc@FreeBSD.org

DOC?= article

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
