#
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/tutorials/Makefile 164 2012-10-04 20:43:02Z ebrandi@fugspbr.org $
#
# Build the FreeBSD tutorials/articles outside of the www tree, and then
# install them in to the right place.

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS = index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
