# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/java/dists/Makefile 164 2012-10-04 20:43:02Z ebrandi@fugspbr.org $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=	15.xml
DOCS+=	16.xml
DOCS+=	17.xml
DOCS+=	index.xml

.include "${DOC_PREFIX}/share/mk/web.site.mk"
