# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/FAQ/Makefile 165 2012-10-04 21:26:02Z ebrandi@fugspbr.org $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DATA=   index.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
