# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/ports/Makefile.inc0 164 2012-10-04 20:43:02Z ebrandi@fugspbr.org $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif
.if exists(Makefile.inc)
.include "Makefile.inc"
.endif

.if exists(Makefile.gen)
.include "Makefile.gen"
.endif

.include "${DOC_PREFIX}/share/mk/web.site.mk"
