# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/ports/growth/Makefile 164 2012-10-04 20:43:02Z ebrandi@fugspbr.org $
#

TOOLDIR=${.CURDIR}/../../../../share/tools/portsgrowth

all install clean:
	cd ${TOOLDIR}; \
		 ${MAKE} ${MAKEFLAGS} ${.TARGETS}

