# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/htdocs/docproj/Makefile 164 2012-10-04 20:43:02Z ebrandi@fugspbr.org $

.if exists(../Makefile.conf)
.include "../Makefile.conf"
.endif
.if exists(../Makefile.inc)
.include "../Makefile.inc"
.endif

DOCS=   current.xml
DOCS+=	doc-set.xml
DOCS+=	handbook.xml
DOCS+=	handbook3.xml
DOCS+=  sgml.xml
DOCS+=  submitting.xml
DOCS+=  who.xml
DOCS+=  translations.xml
DOCS+=	docproj.xml
DOCS+=	todo.xml

INDEXLINK= docproj.html

.include "${DOC_PREFIX}/share/mk/web.site.mk"
