# 
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/articles/linux-users/Makefile 165 2012-10-04 21:26:02Z ebrandi@fugspbr.org $
#
# Article: FreeBSD Quickstart for Linux Users

DOC?= article

FORMATS?= html html-split
WITH_ARTICLE_TOC?= YES

INSTALL_COMPRESSED?= gz
INSTALL_ONLY_COMPRESSED?=

SRCS=	article.xml

URL_RELPREFIX?=	../../../..
DOC_PREFIX?=	${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
