#
# Build the FreeBSD FAQ
#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: r38826
#
# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/articles/Makefile 165 2012-10-04 21:26:02Z ebrandi@fugspbr.org $

SUBDIR =
SUBDIR+= building-products
SUBDIR+= contributing
SUBDIR+= contributing-ports
SUBDIR+= explaining-bsd
SUBDIR+= freebsd-questions
SUBDIR+= freebsd-update-server
SUBDIR+= hubs
SUBDIR+= linux-users
SUBDIR+= new-users
SUBDIR+= portbuild
SUBDIR+= problem-reports

DOC_PREFIX?= ${.CURDIR}/../..
.include "${DOC_PREFIX}/share/mk/doc.project.mk"
