# $FreeBSD: trunk/docs/pt_BR.ISO8859-1/articles/contributing/Makefile 165 2012-10-04 21:26:02Z ebrandi@fugspbr.org $
#
# The FreeBSD Documentation Project
# The FreeBSD Brazilian Portuguese Documentation Project
#
# Original revision: r38826
#

DOC?= article

FORMATS?= html html-split

INSTALL_COMPRESSED?=gz
INSTALL_ONLY_COMPRESSED?=

WITH_ARTICLE_TOC?=YES

SRCS= article.xml

DOC_PREFIX?= ${.CURDIR}/../../..

.include "${DOC_PREFIX}/share/mk/doc.project.mk"
